project:
  type: website
  output-dir: docs

website:
  title: "Danielle Navarro"
  sidebar: 
    style: "docked"
    search: false
    contents:
      - section: "Contact"
        contents:
          - href: https://fosstodon.org/@djnavarro
            text: fosstodon.org/@djnavarro
          - href: https://github.com/djnavarro
            text: github.com/djnavarro
          - href: mailto:djnavarro@protonmail.com
            text: djnavarro@protonmail.com
  
      - section: "Sites"
        contents:
          - href: https://art.djnavarro.net
            text: art.djnavarro.net
          - href: https://blog.djnavarro.net
            text: blog.djnavarro.net
          - href: https://slides.djnavarro.net
            text: slides.djnavarro.net

format:
  html:
    theme: [darkly, tweaks.scss]
    css: styles.css
    toc: true

editor: visual

