project:
  type: website
  output-dir: docs
  post-render: ./post-render.sh

website:
  title: "Danielle Navarro"
  site-url: https://djnavarro.net
  repo-url: https://github.com/djnavarro/djnavarro.github.io
  open-graph: true
  search: false
  twitter-card:
    creator: "@djnavarro"
    card-style: summary_large_image
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: ./about/index.qmd
        text: About
      - href: ./contact/index.qmd
        text: Contact
      - href: https://cv.djnavarro.net
        text: Résumé
    right:
      - text: Sites
        menu:
        - href: https://djnavarro.net
          text: Homepage
        - href: https://blog.djnavarro.net
          text: Data science blog
        - href: https://art.djnavarro.net
          text: Generative art
        - href: https://papers.djnavarro.net
          text: Academic papers
        - href: https://djnavarro.net/sites
          text: More...
  page-footer:
    center:
      - href: https://djnavarro.net
        text: djnavarro.net

format:
  html:
    respect-user-color-scheme: true
    theme: 
      dark: ash.scss
      light: ember.scss
    css: styles.css
    include-after-body: plausible.html


