project:
  type: website
  output-dir: docs

website:
  title: "Danielle Navarro"
  sidebar: 
    style: "docked"
    search: false
    contents:
      - section: "Contact"
        contents:
          - href: https://fosstodon.org/@djnavarro
            text: fosstodon.org/@djnavarro
          - href: https://github.com/djnavarro
            text: github.com/djnavarro
          - href: mailto:djnavarro@protonmail.com
            text: djnavarro@protonmail.com
  
      - section: "Sites"
        contents:
          - href: https://art.djnavarro.net
            text: art.djnavarro.net
          - href: https://blog.djnavarro.net
            text: blog.djnavarro.net
          - href: https://slides.djnavarro.net
            text: slides.djnavarro.net
          - href: https://arrow-user2022.netlify.app
            text: arrow-user2022.netlify.app
          - href: https://art-from-code.netlify.app
            text: art-from-code.netlify.app
          - href: https://essays.djnavarro.net
            text: essays.djnavarro.net
          - href: https://papers.djnavarro.net
            text: papers.djnavarro.net
          - href: https://learningstatsticswithr.com
            text: learningstatisticswithr.com
      - section: "Packages"
        contents:
          - href: https://queue.djnavarro.net
            text: queue.djnavarro.net
          - href: https://flametree.djnavarro.net
            text: flametree.djnavarro.net
          - href: https://jasmines.djnavarro.net
            text: jasmines.djnavarro.net
      

format:
  html:
    theme: [darkly, tweaks.scss]
    css: styles.css
    toc: true

editor: visual

