---
name: Danielle
surname: Navarro
position: "Associate Professor of Cognitive Science, UNSW Sydney"
phone: +61 421 488 402
www: djnavarro.net
email: d.navarro@unsw.edu.au
twitter: djnavarro
github: djnavarro
linkedin: djnavarro
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

\tolerance=1
\emergencystretch=\maxdimen
\hyphenpenalty=10000
\hbadness=10000

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some biographical detail

I spent my youth living in rural Australia during the 1980s, and have been living in Sydney for the last several years. Professionally I work as an academic cognitive scientist ([**djnavarro.net**](https://djnavarro.net)), studying the mathematical and computational basis for human learning and reasoning. As a happy side-effect of this work, I've learned a lot of data science and statistics, and despite being very successful in my original field I am now better known for my data science work than my contributions to mathematical psychology and cognitive science! 

My educational and employment history is as follows: My PhD was awarded in 2003 by the University of Adelaide, where I was appointed Lecturer in 2006, promoted to Senior Lecturer in 2009 and Associate Professor in 2013. From 2007-2015 I held multiple Australian Research Council Fellowships, prestigious well-funded research positions awarded via competitive grant processes. From 2016 have been an Associate Professor at UNSW Sydney. 

On the side, I make generative art in R ([**art.djnavarro.net**](https://art.djnavarro.net)).

# Coding and workflow

My code is written mostly in R, with a light sprinkle of C++ when speed is necessary. For web programming I rely on javascript HTML and CSS, focusing on libraries such as jsPsych designed specifically for my use case, and use plumber and Shiny at times when I need web applications to rely on R code. I make extensive use of Hugo and associated literate programming tools in R (blogdown, hugodown, rmarkdown etc), and have experience writing Hugo themes. I have previous experience with Matlab/Octave, and familiarity with Python.

In my academic day job and my art, I find it useful to write R packages. I've written several packages (as an example, see [**jaysire.djnavarro.net**](https://jaysire.djnavarro.net/)) and in doing so have become skilled in using standard developer tools (usethis, testthat, pkgdown etc). I am comfortable working with git/GitHub and associated R tools (gert, git2r, etc). 

In addition to software development, my scientific work requires me to engage in data wrangling, analysis, visualisation and statistical modelling on an everyday basis. For most everyday data cleaning, analysis and visualisation tasks I use tidyverse extensively. For modelling work, my workflow is a little more varied: I have some experience using tidymodels tools, but for the most part my workflow is based around using JAGS and Stan to implement Bayesian data analyses. As a method of last resort, in cases where the inference task requires a highly specific model that is not amenable to standard tools, I have implemented my own custom models.

# Reporting and communication

As an academic, most of my reports are written as papers in technical journals. Across my career I have written approximately 150 academic papers ([**scholar.djnavarro.net**](http://scholar.djnavarro.net)), and in the course of writing them I have become an accomplished technical writer. My favourite example is a brief paper, *"Between the devil and the deep blue sea: Tensions between scientific judgement and statistical model selection"* ([**psyarxiv.com/39q8y**](https://psyarxiv.com/39q8y/)). The paper has a strong authorial voice, takes a broad perspective on a difficult problem, and uses technical concepts (e.g., large sample behaviour of the Bayes factor when all models are wrong) while remaining accessible to a broad audience. 

One aspect to my communiction of which I am especially proud is the ability to adapt my writing style to context. For example, I have written technical books for a broader audience, most notably  [**learningstatisticswithr.com**](https://learningstatisticswithr.com), which is highly regarded for its prose, clarity and humour. In contrast, my contributions to the forthcoming 3rd edition of the ggplot2 book adopt the "house style" which favours brevity as well as clarity ([**ggplot2-book.org**](https://ggplot2-book.org/)). 

In addition to written communication and reporting skills, my work has required me to become adept at public speaking (e.g., [**youtu.be/BQMDOxWGrQg**](https://youtu.be/BQMDOxWGrQg)), running small workshops, creating tutorial videos, and teaching formal and informal classes across a wide range of topics.

# Training, mentoring, and interpersonal skills

I have been a professional educator for over 15 years, teaching classes in data science, statistics, cognitive science, and other areas ([**djnavarro.net/teaching**](https://djnavarro.net/teaching/)). I am a certified tidyverse instructor, the author of an award winning open access statistics textbook, and make course materials publicly available in a variety of formats (e.g., [**youtube.com/daniellenavarro77**](https://www.youtube.com/daniellenavarro77)). I've run summer schools aimed at teaching statistical programming in R to social scientists ([**chdsummerschool.com**](https://chdsummerschool.com/)), and have experience teaching large and small groups. 

In addition to university and summer school teaching, I have been privileged to serve as advisor for approximately 40 graduate students, honours (advanced undergraduate) students and postdoctoral researchers, who have brought a broad range of interests, nationalities, and skills to the table. I have advised mathematicians, computer scientists, psychologists, statisticians and more. Some are coding experts, others are novices: I am always prepared to meet people where they are, at any stage in their journey. I am endlessly passionate about and experienced in helping them to their next stage, whatever that may be. The happiest moments in my career have been those when my former students have taken on academic positions of their own, won awards for work that I advised on, or simply achieved something they otherwise would not have thought possible.

My experience has been that this work requires teamwork, strong interpersonal skills, and the ability to listen to others with empathy, even when they disagree with me in heated terms. My previous leadership roles on academic committees, formal leadership training, and experience running a research group have all helped me develop these skills, as one might expect. Perhaps less obviously, my life as a parent has taught me a lot about patience, living with ambiguity, and the nature of conflict and diplomacy.

# Project management and team building

Across my academic career I have managed a team of researchers that I have funded through national competitive grants and private research contracts (8 major grants totalling $3 million, and many smaller contracts). Securing this funding requires the ability to develop and implement complex research plans spanning multiple years and coordinating the activities of a team of diverse researchers, building shared goals for a team, and so on. 

In terms of larger projects, I have twice been involved in "Centre of Excellence" bids, once as a senior named investigator. These bids are larger scale grants worth tens of millions of dollars over several years. Organising an application is a complex process that requires the co-ordination of multiple universities, companies and government departments. Dozens of academics are typically involved, research agreements are required, and governance structures need to be designed before a bid can be considered. Both bids I was involved in reached the final stage of the selection process (itself a major achievement!), and this work taught me the importance of oversight, governance, and developing organisational structures suited to the context.

# Diversity and inclusion

Perhaps unsurprisingly, diversity and inclusion is a subject dear to my heart as a transgender woman in academia. During my career I've taken on administrative roles within equity committees, spoken on panels about LGBTIQ inclusion, and at times been a public advocate for transgender inclusion. I cofounded the Sydney R-Ladies chapter ([**rladiessydney.org**](https://rladiessydney.org/)), and have authored papers articulating a vision for what a truly open and inclusive psychology might look like ([**psyarxiv.com/gdzue**](https://psyarxiv.com/gdzue)). Though this work is difficult, it is incredibly rewarding.

Part of my drive to do this work stems from my own hope to see a better world: I view diversity and inclusion as an inherent good, to be valued for its own sake. This perspective leads to practical consequences and policy implications at an institutional level: when an organisation omits or ignores the perspectives of marginalised populations it inevitably perpetuates and perhaps exacerbates existing problems. Being transgender, I often notice hidden assumptions and dangers that other people might not. Being white, I often fail to notice problems that are easily detected by people of colour. Diversity helps an organisation avoid these mistakes, and in doing so contribute more effectively to the public good. 

# Breadth of perspective

A characteristic to how I work is not simply to aim for rigour in what I do, but also to take a broad perspective on science, statistics and how systems operate. This is reflected in academic writing and talks I have given about the nature of science, statistics and inference ([**youtu.be/tNkmsAOn7aU**](https://youtu.be/tNkmsAOn7aU)), for instance. It is also something that has afforded me the opportunity to take on my current editorial roles at one of the top journals in all of science ([**Science**](https://www.sciencemag.org/)) as well as the top theoretical journal in my field ([**Psychological Review**](https://www.apa.org/pubs/journals/rev/)). As a consequence of this editorial work, I have been able to appreciate a wide variety of different scientific perspectives, methods and concepts. This skill is something I hope to bring to any future work I engage in.


